export enum AppCommonVocabulary {
  docNumber = 'Номер',
  actions = 'Действия',
  chosen = 'Выбрано',
  showFilter = 'Открыть фильтр',
  clear = 'Очистить',
  chosenFilters = 'Выбранные фильтры',
  submit = 'Применить',
  filterTitle = 'Фильтр',
  notEntered = 'Не введено',
  create = 'Создать',
  registryCode = 'Код по Сводному реестру',
  budgetCode = 'Код бюджета',
  orgName = 'Наименование организации',
  tofkBankAccount = 'Номер счета ТОФК',
  tofkCode = 'Код ТОФК',
  tofkName = 'Наименование ТОФК',
  dataPeriod = 'Дата',
  status = 'Статус',
  inn = 'ИНН',
  kpp = 'КПП',
  amountFunds = 'Сумма денежных средств',
  cardNumber = 'Номер банковской карты',
  personalAccount = 'Лицевой счет',
  upload = 'Загрузить',
  cancel = 'Отменить',
}
