export enum PaymentOrderKey {
  docSource = 'docSource',
  main = 'main',
  status = 'status',
  currentStatus = 'currentStatus',
  docNumber = 'docNumber',
  docDate = 'docDate',
  createdTs = 'createdTs',
  amount = 'amount',
  isOnRecord = 'isOnRecord',
  additionalInformation = 'additionalInformation',
  bankReport = 'bankReport',
  exKey = 'exKey',
  objectCode = 'objectCode',
  amountInText = 'amountInText',
  docType = 'docType',
  edNumber = 'edNumber',
  edType = 'edType',
  edDate = 'edDate',
  edId = 'edId',
  typeOfPayment = 'typeOfPayment',
  docOperationType = 'docOperationType',
  document = 'document',
  systemData = 'systemData',
  paymentOrder = 'paymentOrder',
  payer = 'payer',
  payerInn = 'payerInn',
  payerKpp = 'payerKpp',
  payerRegistryCode = 'payerRegistryCode',
  payerName = 'payerName',
  payerPersonalAccount = 'payerPersonalAccount',
  payerBudgetCode = 'payerBudgetCode',
  payerBudgetType = 'payerBudgetType',
  payerOktmoPpo = 'payerOktmoPpo',
  payerOrgName = 'payerOrgName',
  payerBankDetails = 'payerBankDetails',
  payerBankAccount = 'payerBankAccount',
  payerBik = 'payerBik',
  payerBankName = 'payerBankName',
  payerCardNumber = 'payerCardNumber',
  payerCorBankAccount = 'payerCorBankAccount',
  payerServiceTofkCode = 'payerServiceTofkCode',
  payerOrderNumber = 'payerOrderNumber',
  payerOrderDate = 'payerOrderDate',
  accountCode = 'accountCode',
  accountingCs = 'accountingCs',
  recipient = 'recipient',
  recipientCardNumber = 'recipientCardNumber',
  recipientRegistryCode = 'recipientRegistryCode',
  recipientName = 'recipientName',
  recipientInn = 'recipientInn',
  recipientKpp = 'recipientKpp',
  recipientPersonalAccount = 'recipientPersonalAccount',
  recipientTofkCode = 'recipientTofkCode',
  recipientTofkName = 'recipientTofkName',
  recipientBudgetCode = 'recipientBudgetCode',
  recipientBudgetType = 'recipientBudgetType',
  recipientOktmoPpo = 'recipientOktmoPpo',
  recipientOrgName = 'recipientOrgName',
  recipientServiceTofkCode = 'recipientServiceTofkCode',
  accountNumber = 'accountNumber',
  baTofkCode = 'baTofkCode',
  recipientBankDetails = 'recipientBankDetails',
  recipientBankAccount = 'recipientBankAccount',
  recipientBik = 'recipientBik',
  recipientBankName = 'recipientBankName',
  recipientCorBankAccount = 'recipientCorBankAccount',
  paymentInfo = 'paymentInfo',
  typeOfOperation = 'typeOfOperation',
  paymentPriority = 'paymentPriority',
  receiptDate = 'receiptDate',
  putInFileDate = 'putInFileDate',
  writtenOffDate = 'writtenOffDate',
  paymentTerm = 'paymentTerm',
  paymentPurpose = 'paymentPurpose',
  paymentSource = 'paymentSource',
  code = 'code',
  taxPayments = 'taxPayments',
  payerStatus = 'payerStatus',
  kbk = 'kbk',
  oktmoCode = 'oktmoCode',
  paymentReason = 'paymentReason',
  taxPeriod = 'taxPeriod',
  taxDocNumber = 'taxDocNumber',
  taxDocDate = 'taxDocDate',
  payoutCode = 'payoutCode',
  reserveField = 'reserveField',
  taxPurposeOfPayment = 'taxPurposeOfPayment',
  exAdditionalInformationKey = 'exAdditionalInformationKey',
  addDocCode = 'addDocCode',
  addDocument = 'addDocument',
  addAmount = 'addAmount',
  addPersonalAccount = 'addPersonalAccount',
  addCardNumber = 'addCardNumber',
  addRegistryCode = 'addRegistryCode',
  fundsTypeCode = 'fundsTypeCode',
  orfkMark = 'orfkMark',
  bankDate = 'bankDate',
  bankLight = 'bankLight',
  color = 'color',
  info = 'info',
  primaryDocCode = 'primaryDocCode',
  primaryDocName = 'primaryDocName',
  primaryDocShortName = 'primaryDocShortName',
  primaryDocKey = 'primaryDocKey',
  primaryRowKey = 'primaryRowKey',
  purposeCode = 'purposeCode',
  oks = 'oks',
  autoControlResult = 'autoControlResult',
  isBlocked = 'isBlocked',
  blockedReason = 'blockedReason',
  actions = 'actions',
  printFormList = 'printFormList',
  attachmentList = 'attachmentList',
  approvalList = 'approvalList',
}

export const PaymentOrderFormVocabulary: Partial<Record<PaymentOrderKey, string>> = {
  [PaymentOrderKey.payerInn]: 'ИНН',
  [PaymentOrderKey.payerKpp]: 'КПП',
  [PaymentOrderKey.payerPersonalAccount]: 'Лицевой счет',
  [PaymentOrderKey.payerRegistryCode]: 'Код по сводному реестру',
  [PaymentOrderKey.payerName]: 'Наименование плательщика',
  [PaymentOrderKey.payerCardNumber]: 'Номер банковской карты',
  [PaymentOrderKey.payerBudgetCode]: 'Код бюджета л/с',
  [PaymentOrderKey.payerOktmoPpo]: 'ОКТМО ППО',
  [PaymentOrderKey.payerServiceTofkCode]: 'Код ТОФК',
  [PaymentOrderKey.payerBankAccount]: 'Сч. №',
  [PaymentOrderKey.payerBik]: 'БИК',
  [PaymentOrderKey.payerCorBankAccount]: 'Кор. сч. №',
  [PaymentOrderKey.recipientInn]: 'ИНН',
  [PaymentOrderKey.recipientKpp]: 'КПП',
  [PaymentOrderKey.recipientPersonalAccount]: 'Лицевой счет',
  [PaymentOrderKey.recipientRegistryCode]: 'Код по сводному реестру',
  [PaymentOrderKey.recipientName]: 'Наименование получателя',
  [PaymentOrderKey.recipientBudgetCode]: 'Код бюджета л/с',
  [PaymentOrderKey.recipientOktmoPpo]: 'ОКТМО ППО',
  [PaymentOrderKey.recipientServiceTofkCode]: 'Код ТОФК',
  [PaymentOrderKey.recipientBankAccount]: 'Сч. №',
  [PaymentOrderKey.recipientBik]: 'БИК',
  [PaymentOrderKey.recipientCorBankAccount]: 'Кор. сч. №',
  [PaymentOrderKey.kbk]: 'Код бюджетной классификации',
  [PaymentOrderKey.oktmoCode]: 'Код по ОКТМО',
  [PaymentOrderKey.paymentPurpose]: 'Основание платежа',
  [PaymentOrderKey.taxPurposeOfPayment]: 'Наз. пл.',
  [PaymentOrderKey.edType]: 'Вид документа (Тип ЭД)',
  [PaymentOrderKey.paymentPriority]: 'Приоритет платежа',
};

export const PaymentOrdersVocabulary: Partial<Record<PaymentOrderKey, string>> = {
  [PaymentOrderKey.docSource]: 'Источник',
  [PaymentOrderKey.main]: 'Основная информация',
  [PaymentOrderKey.currentStatus]: 'Статус',
  [PaymentOrderKey.docNumber]: 'Номер документа',
  [PaymentOrderKey.docDate]: 'Дата документа',
  [PaymentOrderKey.createdTs]: 'Дата и время загрузки',
  [PaymentOrderKey.amount]: 'Сумма',
  [PaymentOrderKey.isOnRecord]: 'Отражение в учете',
  [PaymentOrderKey.additionalInformation]: 'Связанный документ',
  [PaymentOrderKey.bankReport]: 'Выписка банка',
  [PaymentOrderKey.amountInText]: 'Сумма прописью',
  [PaymentOrderKey.docType]: 'Тип документа',
  [PaymentOrderKey.edNumber]: 'Номер ЭД в течение опер. дня',
  [PaymentOrderKey.edType]: 'Вид документа',
  [PaymentOrderKey.edDate]: 'Дата составления ЭД',
  [PaymentOrderKey.edId]: 'Уникальный идентификатор составителя ЭД',
  [PaymentOrderKey.typeOfPayment]: 'Вид платежа',
  [PaymentOrderKey.docOperationType]: 'Тип операции',
  [PaymentOrderKey.paymentOrder]: 'Платежное поручение',
  [PaymentOrderKey.payer]: 'Плательщик',
  [PaymentOrderKey.payerInn]: 'ИНН плательщика',
  [PaymentOrderKey.payerKpp]: 'КПП плательщика',
  [PaymentOrderKey.payerRegistryCode]: 'Код по Сводному реестру плательщика',
  [PaymentOrderKey.payerName]: 'Наименование плательщика',
  [PaymentOrderKey.payerPersonalAccount]: 'Лицевой счет плательщика',
  [PaymentOrderKey.payerBudgetCode]: 'Код бюджета л/с плательщика',
  [PaymentOrderKey.payerBudgetType]: 'Тип бюджета плательщика',
  [PaymentOrderKey.payerCardNumber]: 'Номер банковской карты',
  [PaymentOrderKey.payerOktmoPpo]: 'ОКТМО ППО плательщика',
  [PaymentOrderKey.payerOrgName]: 'Наименование клиента',
  [PaymentOrderKey.payerBankDetails]: 'Реквизиты банка плательщика',
  [PaymentOrderKey.payerBankAccount]: '№ счета плательщика',
  [PaymentOrderKey.payerBik]: 'БИК банка плательщика',
  [PaymentOrderKey.payerBankName]: 'Банк плательщика',
  [PaymentOrderKey.payerCorBankAccount]: 'Корреспондентский счёт банка плательщика',
  [PaymentOrderKey.payerServiceTofkCode]: 'Код ТОФК/ФО по месту обслуживания ЛС',
  [PaymentOrderKey.payerOrderNumber]: 'Номер распоряжения',
  [PaymentOrderKey.payerOrderDate]: 'Дата составления распоряжения',
  [PaymentOrderKey.accountCode]: 'Учетный код плательщика',
  [PaymentOrderKey.accountingCs]: 'ЦС учета',
  [PaymentOrderKey.recipient]: 'Получатель',
  [PaymentOrderKey.recipientName]: 'Наименование получателя',
  [PaymentOrderKey.recipientCardNumber]: 'Номер банковской карты',
  [PaymentOrderKey.recipientRegistryCode]: 'Код по Сводному реестру клиента',
  [PaymentOrderKey.recipientInn]: 'ИНН получателя',
  [PaymentOrderKey.recipientKpp]: 'КПП получателя',
  [PaymentOrderKey.recipientTofkCode]: 'Код ТОФК',
  [PaymentOrderKey.recipientTofkName]: 'Наименование ТОФК',
  [PaymentOrderKey.recipientPersonalAccount]: 'Лицевой счет получателя',
  [PaymentOrderKey.recipientBudgetCode]: 'Код бюджета л/с получателя',
  [PaymentOrderKey.recipientBudgetType]: 'Тип бюджета получателя',
  [PaymentOrderKey.recipientOktmoPpo]: 'ОКТМО ППО получателя',
  [PaymentOrderKey.recipientOrgName]: 'Наименование клиента получателя',
  [PaymentOrderKey.recipientServiceTofkCode]: 'Код ТОФК/ФО по месту обслуживания ЛС',
  [PaymentOrderKey.accountNumber]: 'Учетный номер',
  [PaymentOrderKey.baTofkCode]: 'Код ТОФК БС',
  [PaymentOrderKey.recipientBankDetails]: 'Реквизиты банка получателя',
  [PaymentOrderKey.recipientBankAccount]: '№ счета получателя',
  [PaymentOrderKey.recipientBik]: 'БИК банка получателя',
  [PaymentOrderKey.recipientBankName]: 'Банк получателя',
  [PaymentOrderKey.recipientCorBankAccount]: 'Корреспондентский счёт банка получателя',
  [PaymentOrderKey.paymentInfo]: 'Информация о платеже',
  [PaymentOrderKey.typeOfOperation]: 'Вид операции',
  [PaymentOrderKey.paymentPriority]: 'Очередность платежа',
  [PaymentOrderKey.receiptDate]: 'Поступ. в банк плат.',
  [PaymentOrderKey.putInFileDate]: 'Дата помещения в картотеку',
  [PaymentOrderKey.writtenOffDate]: 'Списано со сч. плат.',
  [PaymentOrderKey.paymentTerm]: 'Срок платежа',
  [PaymentOrderKey.paymentPurpose]: 'Назначение платежа',
  [PaymentOrderKey.paymentSource]: 'Источник оплаты',
  [PaymentOrderKey.code]: 'Код',
  [PaymentOrderKey.taxPayments]: 'Налоговые платежи',
  [PaymentOrderKey.payerStatus]: 'Статус плательщика',
  [PaymentOrderKey.kbk]: 'КБК',
  [PaymentOrderKey.oktmoCode]: 'ОКТМО',
  [PaymentOrderKey.paymentReason]: 'Основание платежа',
  [PaymentOrderKey.taxPeriod]: 'Налоговый период',
  [PaymentOrderKey.taxDocNumber]: 'Номер документа',
  [PaymentOrderKey.taxDocDate]: 'Дата документа',
  [PaymentOrderKey.payoutCode]: 'Код выплаты',
  [PaymentOrderKey.reserveField]: 'Резервное поле',
  [PaymentOrderKey.taxPurposeOfPayment]: 'Назначение платежа по налоговым платежам',
  [PaymentOrderKey.exAdditionalInformationKey]: 'Ключ логической ссылки на запись дополнительной информации',
  [PaymentOrderKey.addDocCode]: 'Код связного документа',
  [PaymentOrderKey.addDocument]: 'Связанный документ',
  [PaymentOrderKey.addAmount]: 'Сумма из связанного документа',
  [PaymentOrderKey.addPersonalAccount]: 'Номер ЛС из связанного документа',
  [PaymentOrderKey.addCardNumber]: 'Номер карты из связанного документа',
  [PaymentOrderKey.addRegistryCode]: 'Код по Сводному реестру из связанного документа',
  [PaymentOrderKey.fundsTypeCode]: 'Вид средств',
  [PaymentOrderKey.orfkMark]: 'Отметки ОрФК',
  [PaymentOrderKey.bankDate]: 'Дата исполнения в банке',
  [PaymentOrderKey.bankLight]: 'Фонарная группа "Банк"',
  [PaymentOrderKey.color]: 'Цвет индикатора',
  [PaymentOrderKey.info]: 'Комментарий',
  [PaymentOrderKey.primaryDocCode]: 'Код первичного документа клиента',
  [PaymentOrderKey.primaryDocShortName]: 'Документ-основание',
  [PaymentOrderKey.primaryDocName]: 'Наименование первичного документа',
  [PaymentOrderKey.primaryDocKey]: 'Идентификатор первичного документа клиента',
  [PaymentOrderKey.primaryRowKey]: 'Номер строки родительского документа',
  [PaymentOrderKey.purposeCode]: 'Код цели (аналитический код)',
  [PaymentOrderKey.oks]: 'ОКС (КМИ)',
};
