import { PaymentOrderKey } from '../types';

export const paymentOrdersItemTemplate = {
  [PaymentOrderKey.status]: null,
  [PaymentOrderKey.currentStatus]: null,
  [PaymentOrderKey.document]: {
    [PaymentOrderKey.docSource]: null,
    [PaymentOrderKey.docNumber]: null,
    [PaymentOrderKey.docDate]: null,
    [PaymentOrderKey.amount]: 0,
    [PaymentOrderKey.amountInText]: null,
    [PaymentOrderKey.docType]: null,
    [PaymentOrderKey.typeOfPayment]: null,
    [PaymentOrderKey.paymentPriority]: null,
    [PaymentOrderKey.edId]: null,
    [PaymentOrderKey.edType]: null,
    [PaymentOrderKey.docOperationType]: null,
    [PaymentOrderKey.bankLight]: {
      [PaymentOrderKey.color]: null,
      [PaymentOrderKey.info]: null,
    },
    [PaymentOrderKey.paymentOrder]: {
      [PaymentOrderKey.payer]: {
        [PaymentOrderKey.payerInn]: null,
        [PaymentOrderKey.payerKpp]: null,
        [PaymentOrderKey.payerName]: null,
        [PaymentOrderKey.payerPersonalAccount]: null,
        [PaymentOrderKey.payerOrgName]: null,
        [PaymentOrderKey.payerRegistryCode]: null,
        [PaymentOrderKey.payerCardNumber]: null,
        [PaymentOrderKey.payerBudgetCode]: null,
        [PaymentOrderKey.payerBudgetType]: null,
        [PaymentOrderKey.payerOktmoPpo]: null,
        [PaymentOrderKey.payerServiceTofkCode]: null,
        [PaymentOrderKey.accountCode]: null,
        [PaymentOrderKey.accountingCs]: null,
      },
      [PaymentOrderKey.payerBankDetails]: {
        [PaymentOrderKey.payerBankAccount]: null,
        [PaymentOrderKey.payerBik]: null,
        [PaymentOrderKey.payerBankName]: null,
        [PaymentOrderKey.payerCorBankAccount]: null,
        [PaymentOrderKey.payerOrderNumber]: null,
        [PaymentOrderKey.payerOrderDate]: null,
      },
      [PaymentOrderKey.recipient]: {
        [PaymentOrderKey.recipientName]: null,
        [PaymentOrderKey.recipientInn]: null,
        [PaymentOrderKey.recipientKpp]: null,
        [PaymentOrderKey.recipientPersonalAccount]: null,
        [PaymentOrderKey.recipientRegistryCode]: null,
        [PaymentOrderKey.recipientBudgetCode]: null,
        [PaymentOrderKey.recipientBudgetType]: null,
        [PaymentOrderKey.recipientOktmoPpo]: null,
        [PaymentOrderKey.recipientServiceTofkCode]: null,
      },
      [PaymentOrderKey.recipientBankDetails]: {
        [PaymentOrderKey.recipientBankAccount]: null,
        [PaymentOrderKey.recipientBik]: null,
        [PaymentOrderKey.recipientBankName]: null,
        [PaymentOrderKey.recipientCorBankAccount]: null,
      },
      [PaymentOrderKey.paymentInfo]: {
        [PaymentOrderKey.typeOfOperation]: null,
        [PaymentOrderKey.paymentPriority]: null,
        [PaymentOrderKey.paymentPurpose]: null,
        [PaymentOrderKey.code]: null,
        [PaymentOrderKey.receiptDate]: null,
        [PaymentOrderKey.putInFileDate]: null,
        [PaymentOrderKey.writtenOffDate]: null,
        [PaymentOrderKey.paymentTerm]: null,
        [PaymentOrderKey.paymentSource]: null,
      },
      [PaymentOrderKey.taxPayments]: {
        [PaymentOrderKey.payerStatus]: null,
        [PaymentOrderKey.kbk]: null,
        [PaymentOrderKey.oktmoCode]: null,
        [PaymentOrderKey.paymentPurpose]: null,
        [PaymentOrderKey.taxPeriod]: null,
        [PaymentOrderKey.taxDocNumber]: null,
        [PaymentOrderKey.taxDocDate]: null,
        [PaymentOrderKey.payoutCode]: null,
        [PaymentOrderKey.reserveField]: null,
        [PaymentOrderKey.taxPurposeOfPayment]: null,
      },
      [PaymentOrderKey.additionalInformation]: {
        [PaymentOrderKey.fundsTypeCode]: null,
        [PaymentOrderKey.primaryDocCode]: null,
        [PaymentOrderKey.primaryDocShortName]: null,
        [PaymentOrderKey.primaryDocKey]: null,
        [PaymentOrderKey.primaryDocName]: null,
        [PaymentOrderKey.primaryRowKey]: null,
        [PaymentOrderKey.purposeCode]: null,
        [PaymentOrderKey.kbk]: null,
        [PaymentOrderKey.oks]: null,
      },
      [PaymentOrderKey.orfkMark]: {
        [PaymentOrderKey.bankDate]: null,
      },
      [PaymentOrderKey.bankLight]: {
        [PaymentOrderKey.color]: null,
        [PaymentOrderKey.info]: null,
      },
    },
    [PaymentOrderKey.attachmentList]: [],
  },
  [PaymentOrderKey.exKey]: null,
  [PaymentOrderKey.objectCode]: null,
  [PaymentOrderKey.systemData]: {
    createdTs: null,
    updatedTs: null,
    isSystem: null,
    createdBy: {
      lastName: null,
      firstName: null,
      middleName: null,
    },
    [PaymentOrderKey.printFormList]: [],
    [PaymentOrderKey.autoControlResult]: null,
  },
  [PaymentOrderKey.printFormList]: [],
  [PaymentOrderKey.isBlocked]: false,
  [PaymentOrderKey.blockedReason]: null,
  [PaymentOrderKey.actions]: [],
  [PaymentOrderKey.approvalList]: [],
};
