import { StatusColors } from '@ebp/vue-ui-lib';

export enum DocumentStatus {
  DRAFT = 'DRAFT',
  CREATED = 'CREATED',
  PREPARED = 'PREPARED',
  TO_IMPROVE = 'TO_IMPROVE',
  HEAD_ACC_SIGNING = 'HEAD_ACC_SIGNING',
  CHIEF_SIGNING = 'CHIEF_SIGNING',
  TO_APPROVE = 'TO_APPROVE',
  APPROVAL = 'APPROVAL',
  APPROVED = 'APPROVED',
  CHECKED = 'CHECKED',
  CANCELED = 'CANCELED',
  REFUSED = 'REFUSED',
  VERIFIED = 'VERIFIED',
  PARTIALLY_VERIFIED = 'PARTIALLY_VERIFIED',
  DELETED = 'DELETED',
  CONFIRMED = 'CONFIRMED',
  CLASSIFIED = 'CLASSIFIED',
  UNCLASSIFIED = 'UNCLASSIFIED',
  MARKED_AS_UNCLARIFIED = 'MARKED_AS_UNCLARIFIED',
  TOFK_ACCEPTED = 'TOFK_ACCEPTED',
  TOFK_HEAD_ACC_SIGNING = 'TOFK_HEAD_ACC_SIGNING',
  TOFK_CHIEF_SIGNING = 'TOFK_CHIEF_SIGNING',
  EXECUTED = 'EXECUTED',
  AWAITING_CONFIRM = 'AWAITING_CONFIRM',
  IMPORTED = 'IMPORTED',
  PROCESSED = 'PROCESSED',
  PART_PROCESSED = 'PART_PROCESSED',
  TOFK_PAYMENT_EXECUTION = 'TOFK_PAYMENT_EXECUTION',
  TOFK_EXECUTED = 'TOFK_EXECUTED',
  SENT_BANK = 'SENT_BANK',
  REJECTED_BANK = 'REJECTED_BANK',
  SIGNED = 'SIGNED',
  TOFK_REJECTED = 'TOFK_REJECTED',
}

export const STATUS_COLOR: Record<DocumentStatus, StatusColors> = {
  [DocumentStatus.DRAFT]: 'grey',
  [DocumentStatus.CREATED]: 'grey',
  [DocumentStatus.PREPARED]: 'yellow',
  [DocumentStatus.TO_IMPROVE]: 'orange',
  [DocumentStatus.HEAD_ACC_SIGNING]: 'yellow',
  [DocumentStatus.CHIEF_SIGNING]: 'yellow',
  [DocumentStatus.TO_APPROVE]: 'yellow',
  [DocumentStatus.APPROVAL]: 'yellow',
  [DocumentStatus.APPROVED]: 'yellow',
  [DocumentStatus.CHECKED]: 'grey',
  [DocumentStatus.CANCELED]: 'red',
  [DocumentStatus.REFUSED]: 'red',
  [DocumentStatus.VERIFIED]: 'yellow',
  [DocumentStatus.PARTIALLY_VERIFIED]: 'yellow',
  [DocumentStatus.DELETED]: 'red',
  [DocumentStatus.CONFIRMED]: 'yellow',
  [DocumentStatus.CLASSIFIED]: 'yellow',
  [DocumentStatus.UNCLASSIFIED]: 'yellow',
  [DocumentStatus.MARKED_AS_UNCLARIFIED]: 'yellow',
  [DocumentStatus.TOFK_ACCEPTED]: 'yellow',
  [DocumentStatus.TOFK_HEAD_ACC_SIGNING]: 'yellow',
  [DocumentStatus.TOFK_CHIEF_SIGNING]: 'yellow',
  [DocumentStatus.EXECUTED]: 'yellow',
  [DocumentStatus.AWAITING_CONFIRM]: 'yellow',
  [DocumentStatus.IMPORTED]: 'yellow',
  [DocumentStatus.PROCESSED]: 'green',
  [DocumentStatus.PART_PROCESSED]: 'yellow',
  [DocumentStatus.TOFK_PAYMENT_EXECUTION]: 'yellow',
  [DocumentStatus.TOFK_EXECUTED]: 'yellow',
  [DocumentStatus.SENT_BANK]: 'yellow',
  [DocumentStatus.REJECTED_BANK]: 'yellow',
  [DocumentStatus.SIGNED]: 'yellow',
  [DocumentStatus.TOFK_REJECTED]: 'yellow',
} as const;

export const STATUS_NAME = {
  [DocumentStatus.DRAFT]: 'Проект',
  [DocumentStatus.CREATED]: 'Создан',
  [DocumentStatus.PREPARED]: 'Подготовлен',
  [DocumentStatus.TO_IMPROVE]: 'Требует доработки',
  [DocumentStatus.HEAD_ACC_SIGNING]: 'На подписании гл.бух',
  [DocumentStatus.CHIEF_SIGNING]: 'На подписании руководителем',
  [DocumentStatus.TO_APPROVE]: 'На утверждении',
  [DocumentStatus.APPROVAL]: 'Ожидает согласования',
  [DocumentStatus.APPROVED]: 'Согласован',
  [DocumentStatus.CHECKED]: 'Проверен',
  [DocumentStatus.CANCELED]: 'Отменен',
  [DocumentStatus.REFUSED]: 'Отклонен',
  [DocumentStatus.VERIFIED]: 'Обработан',
  [DocumentStatus.PARTIALLY_VERIFIED]: 'Частично обработан',
  [DocumentStatus.DELETED]: 'Удален',
  [DocumentStatus.CONFIRMED]: 'Подтвержден',
  [DocumentStatus.CLASSIFIED]: 'Классифицирован',
  [DocumentStatus.UNCLASSIFIED]: 'Неклассифицирован',
  [DocumentStatus.MARKED_AS_UNCLARIFIED]: 'Отражен на НВС',
  [DocumentStatus.TOFK_ACCEPTED]: 'Принят к исполнению',
  [DocumentStatus.TOFK_HEAD_ACC_SIGNING]: 'На подписании гл.бух',
  [DocumentStatus.TOFK_CHIEF_SIGNING]: 'На подписании руководителем',
  [DocumentStatus.EXECUTED]: 'Исполнен',
  [DocumentStatus.AWAITING_CONFIRM]: 'Ожидает подтверждения',
  [DocumentStatus.IMPORTED]: 'Создан',
  [DocumentStatus.PROCESSED]: 'Обработан',
  [DocumentStatus.PART_PROCESSED]: 'Обработан частично',
  [DocumentStatus.TOFK_PAYMENT_EXECUTION]: 'Исполнение платежа',
  [DocumentStatus.TOFK_EXECUTED]: 'Исполнен',
  [DocumentStatus.SENT_BANK]: 'Отправлен в банк',
  [DocumentStatus.REJECTED_BANK]: 'Отказан банком',
  [DocumentStatus.SIGNED]: 'Подписан',
  [DocumentStatus.TOFK_REJECTED]: 'Отклонен ТОФК',
};
