/// <reference types="vite/client" />
interface API_ENV {
  readonly VITE_API_APPROVALS: string,
  readonly VITE_API_ATTRACTION: string,
  readonly VITE_API_AUTH: string,
  readonly VITE_API_BANK_EXTENSION_SESSION: string,
  readonly VITE_API_CLARIFICATION: string,
  readonly VITE_API_FILESTORE: string,
  readonly VITE_API_KBRN: string,
  readonly VITE_API_NSI: string,
  readonly VITE_API_NSPK: string,
  readonly VITE_API_ORGANIZATIONS: string,
  readonly VITE_API_PFHD: string,
  readonly VITE_API_PKS: string,
  readonly VITE_API_PPA: string,
  readonly VITE_API_PPS: string,
  readonly VITE_API_PSFK: string,
  readonly VITE_API_RPIS: string,
  readonly VITE_API_RSKP: string,
  readonly VITE_API_SUBSIDY: string,
  readonly VITE_API_SUBSIDY_LIST: string,
  readonly VITE_API_SUZ: string,
  readonly VITE_API_TD: string,
  readonly VITE_API_URD: string,
  readonly VITE_API_ZKS: string,
  readonly VITE_API_RKS: string,
  readonly VITE_API_ZLS: string,
  readonly VITE_API_VLS: string,
  readonly VITE_API_RLS: string,
  readonly VITE_API_BS: string,
  readonly VITE_API_LINKS: string,
  readonly VITE_API_OBLIGATION: string,
  readonly VITE_API_KB: string,
  readonly VITE_API_ID_RNO: string,
  readonly VITE_API_RPIS_DATAMART: string,
  readonly VITE_API_NVS: string,
  readonly VITE_API_EKS: string,
  readonly VITE_API_VKS: string,
  readonly VITE_API_SKS: string,
  readonly VITE_API_RS: string,
  readonly VITE_API_RSKP_BC: string,
  readonly VITE_API_REIMBURSEMENT: string,
  readonly VITE_API_GMP: string,
  readonly VITE_API_GMP_ESMV: string,
  readonly VITE_API_DOM: string,
  readonly VITE_API_USER_PROFILE: string,
  readonly VITE_API_USER_REFERENCE: string,
  readonly VITE_API_LSR: string,
  readonly VITE_API_WIDGETS: string,
  readonly VITE_API_CBS: string,
}

interface ImportMetaEnv extends API_ENV {
  readonly VITE_APP_NAME: string,
}

interface ImportMeta {
  readonly env: ImportMetaEnv,
}
